# Generated by Django 2.1.7 on 2019-04-10 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=128, unique=True)),
                ('teacher_name', models.CharField(max_length=128)),
                ('course_time', models.CharField(max_length=128)),
                ('course_locus', models.CharField(max_length=128)),
                ('course_credit', models.CharField(max_length=128)),
                ('course_introduction', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('content', models.CharField(max_length=512)),
                ('deadline', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='login.course')),
            ],
        ),
        migrations.CreateModel(
            name='SubmitWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit', models.CharField(max_length=1000)),
                ('submit_time', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('identity', models.CharField(choices=[('student', '学生'), ('teacher', '教师'), ('assistant', '助教')], default='学生', max_length=32)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('tel', models.CharField(max_length=128)),
                ('addr', models.CharField(max_length=128)),
                ('number', models.CharField(max_length=128)),
                ('courses', models.ManyToManyField(related_name='users', to='login.course')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['c_time'],
            },
        ),
        migrations.AddField(
            model_name='submitwork',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_sub', to='login.User'),
        ),
        migrations.AddField(
            model_name='submitwork',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submit', to='login.Homework'),
        ),
    ]
