# Generated by Django 2.1.7 on 2019-04-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitwork',
            name='myfile',
            field=models.FileField(default='', upload_to='media'),
            preserve_default=False,
        ),
    ]
