# Generated by Django 2.1.7 on 2019-05-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='privilege_1',
            field=models.CharField(default='0', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='privilege_2',
            field=models.CharField(default='0', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='privilege_3',
            field=models.CharField(default='0', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='privilege_4',
            field=models.CharField(default='0', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='privilege_5',
            field=models.CharField(default='0', max_length=128),
        ),
    ]
