# Generated by Django 2.1.7 on 2019-03-29 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
        migrations.AddField(
            model_name='user',
            name='identity',
            field=models.CharField(choices=[('student', '学生'), ('teacher', '教师'), ('assistant', '助教')], default='学生', max_length=32),
        ),
    ]
