# Generated by Django 2.1.7 on 2019-04-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_locus',
            field=models.CharField(choices=[('(一)101', '(一）101'), ('(一)102', '(一）102'), ('(一)103', '(一）103')], default='(一)101', max_length=128),
        ),
    ]
