# Generated by Django 2.1.7 on 2019-04-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitwork',
            name='grade',
            field=models.CharField(default='未评阅', max_length=64),
        ),
    ]
