# Generated by Django 2.1.7 on 2019-04-27 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_submitwork_grade'),
        ('login', '0002_auto_20190427_1527'),
    ]

    operations = [
    ]
