# Generated by Django 2.1.7 on 2019-05-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190502_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='courses_1',
            field=models.ManyToManyField(related_name='users_1', to='login.course'),
        ),
    ]
