# Generated by Django 2.1.7 on 2019-04-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190415_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitwork',
            name='myfile',
            field=models.FileField(upload_to=''),
        ),
    ]
