# Generated by Django 2.1.7 on 2019-04-01 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_course_course_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_credit',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_intorduction',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_locus',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
