# Generated by Django 2.1.7 on 2019-05-08 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_user_courses_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privilege_1', models.CharField(default='0', max_length=128)),
                ('privilege_2', models.CharField(default='0', max_length=128)),
                ('privilege_3', models.CharField(default='0', max_length=128)),
                ('privilege_4', models.CharField(default='0', max_length=128)),
                ('privilege_5', models.CharField(default='0', max_length=128)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_pri', to='login.course')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='privilege_1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='privilege_2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='privilege_3',
        ),
        migrations.RemoveField(
            model_name='user',
            name='privilege_4',
        ),
        migrations.RemoveField(
            model_name='user',
            name='privilege_5',
        ),
        migrations.AddField(
            model_name='privilege',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pri', to='login.User'),
        ),
    ]
