# Generated by Django 2.1.7 on 2019-04-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20190401_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='roster',
            field=models.ManyToManyField(to='login.User'),
        ),
    ]
