# Generated by Django 2.1.7 on 2019-04-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_remove_course_roster'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(to='login.course'),
        ),
    ]
