# Generated by Django 2.1.7 on 2019-06-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_homework_myfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_credit',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='5', max_length=128),
        ),
    ]
