# Generated by Django 2.1.7 on 2019-06-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20190605_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitwork',
            name='grade',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='未评阅', max_length=64),
        ),
    ]
