# Generated by Django 2.1.7 on 2019-06-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20190605_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitwork',
            name='grade',
            field=models.CharField(default='未评阅', max_length=64),
        ),
    ]
