
# Generated by Django 2.1.7 on 2019-04-09 12:00

# Generated by Django 2.1.7 on 2019-04-09 11:52


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20190406_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('content', models.CharField(max_length=512)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='login.course')),
            ],
        ),
    ]
