# Generated by Django 2.1.7 on 2019-04-10 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_homework'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit', models.CharField(max_length=1000)),
                ('submit_time', models.DateTimeField(auto_now=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_sub', to='login.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='homework',
            name='student',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='submit',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='submit_time',
        ),
        migrations.AddField(
            model_name='submitwork',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submit', to='login.Homework'),
        ),
    ]
