# Generated by Django 2.1.7 on 2019-04-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='deadline',
            field=models.DateTimeField(default='2011-01-01 12:30'),
            preserve_default=False,
        ),
    ]
