# Generated by Django 2.1.7 on 2019-05-08 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posttype',
            field=models.CharField(default='', max_length=64, null=True),
        ),
    ]
