# Generated by Django 2.1.7 on 2019-04-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='message',
            field=models.TextField(default='', max_length=4000),
            preserve_default=False,
        ),
    ]
