# Generated by Django 2.1.7 on 2019-04-02 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': '板块', 'verbose_name_plural': '板块'},
        ),
    ]
