# Generated by Django 2.1.7 on 2019-05-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_post_posttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='kind',
            field=models.CharField(default='讨论&提问', max_length=128),
        ),
    ]
