# Generated by Django 2.1.7 on 2019-04-06 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20190406_1309'),
        ('boards', '0003_auto_20190406_0632'),
    ]

    operations = [
    ]
