# Generated by Django 2.1.7 on 2019-04-06 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_merge_20190406_0646'),
        ('boards', '0003_auto_20190406_1353'),
    ]

    operations = [
    ]
